[package]
name = "rustkeep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
passwords = "3.1.16"
rand = "0.8.5"
rsa = "0.9.6"
